[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_dao = "62qdrtJGP23PwmvAn5c5B9xT1LSgdnq4p1sQsHnKVFhm"

[programs.localnet]
private_dao = "62qdrtJGP23PwmvAn5c5B9xT1LSgdnq4p1sQsHnKVFhm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallets/wallet-keypair.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
